training:
  num_workers: 4
  max_parallel: 2
  data_dir: "./data/preprocessed/"

manu_test:
  num_epochs: [10]
  learning_rate: [0.0003, 0.001, 0.0001]
  batch_size: [512, 256, 128] 
  fold_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

quick_test:
  num_epochs: [5]
  learning_rate: [0.001]
  batch_size: [256]
  fold_id: [0]

full_training:
  num_epochs: [50, 100]
  learning_rate: [0.0003, 0.001, 0.0001]
  batch_size: [512, 256, 128]
  fold_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]